

oc_platform_annonces:
    path:    /annonces/{page}
    defaults:
        _controller: OCPlatformBundle:Advert:annonces
        page: 1
    requirements:
        page: \d*

oc_platform_home:
    path:    /
    defaults: 
        _controller: OCPlatformBundle:Advert:index
    
oc_platform_view:
    path:    /advert/{id}
    defaults: {_controller: OCPlatformBundle:Advert:view}
    requirements:
        id: \d+

oc_platform_add:
    path:    /add
    defaults: {_controller: OCPlatformBundle:Advert:add}
    
oc_platform_edit:
    path:    /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:    /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements: 
        id: \d+

oc_platform_login:
    path:    /login
    defaults:
        _controller: OCPlatformBundle:Advert:login