<?php

namespace OC\PlatformBundle\Repository;

/**
 * BikeImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BikeImageRepository extends \Doctrine\ORM\EntityRepository
{
}
