<?php

namespace OC\PlatformBundle\Repository;

/**
 * BikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BikeRepository extends \Doctrine\ORM\EntityRepository
{
}
