<?php

namespace OC\PlatformBundle\Repository;

/**
 * FddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FddRepository extends \Doctrine\ORM\EntityRepository
{
}
