<?php

namespace OC\PlatformBundle\Repository;

/**
 * FooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooRepository extends \Doctrine\ORM\EntityRepository
{
}
