<?php

namespace OC\PlatformBundle\Repository;

/**
 * GhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhRepository extends \Doctrine\ORM\EntityRepository
{
}
