<?php

namespace OC\PlatformBundle\Repository;

/**
 * JackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JackRepository extends \Doctrine\ORM\EntityRepository
{
}
