<?php

namespace OC\PlatformBundle\Repository;

/**
 * JzjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JzjRepository extends \Doctrine\ORM\EntityRepository
{
}
