<?php

namespace OC\PlatformBundle\Repository;

/**
 * LannonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LannonceRepository extends \Doctrine\ORM\EntityRepository
{
}
