<?php

namespace OC\PlatformBundle\Repository;

/**
 * LoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoRepository extends \Doctrine\ORM\EntityRepository
{
}
