<?php

namespace OC\PlatformBundle\Repository;

/**
 * MyfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyfileRepository extends \Doctrine\ORM\EntityRepository
{
}
